package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/rfizzle/astimate/calibration/rebuild/internal/definition"
	"github.com/rfizzle/astimate/calibration/rebuild/internal/pin"
	"github.com/rfizzle/astimate/calibration/rebuild/internal/selection"
)

// writeReport writes the selection report: the rule's outcome per stratum,
// every candidate checked, taken or rejected with the reason, the members
// of every tree taken, and the modules a tree selection left out
// (skipped).
func writeReport(path string, def *definition.Definition, verdicts []selection.Verdict, skipped []string, date string) error {
	tree := def.UnitOrDefault() == definition.UnitTree
	what, command, title := "package", "select", ""
	if tree {
		what, command, title = "tree", "select --unit tree", " (trees)"
	}
	var b strings.Builder
	b.WriteString("# Rebuild experiment selection" + title + "\n\n")
	b.WriteString("Generated by `go run ./calibration/rebuild " + command + "` on " + date + " with " + def.GoVersion +
		" (" + strings.Join(def.Env, " ") + "); do not edit by hand. The rule is in README.md.\n\n")
	fmt.Fprintf(&b, "%d experiments from %s, estimated under `%s`.\n\n", len(def.Experiments), def.Source, def.ConfigVersion)
	b.WriteString("Every taken " + what + " was checked at its pin: the oracle passed on the original tree, " +
		"stubbing twice gave byte-identical files, the stubbed module built with `go build ./...`, " +
		"and the oracle's tests built, started (no package initialization panicked) and failed on the stub.\n\n")
	b.WriteString("## Taken\n\n| Stratum | " + strings.ToUpper(what[:1]) + what[1:] + " |")
	if tree {
		b.WriteString(" Packages |")
	}
	b.WriteString(" agent_passes | rebuild_tokens | Oracle tests | Compiles | Tests fail |\n| --- | --- |")
	if tree {
		b.WriteString(" --- |")
	}
	b.WriteString(" --- | --- | --- | --- | --- |\n")
	for _, v := range verdicts {
		if !v.OK {
			continue
		}
		e := v.Experiment
		fmt.Fprintf(&b, "| %s | `%s` |", v.Stratum, e.Package)
		if tree {
			fmt.Fprintf(&b, " %d |", len(e.Members))
		}
		fmt.Fprintf(&b, " %.1f | %d | %s | yes | yes |\n", e.AgentPasses, e.RebuildTokens, testsCell(e.Oracle.Test))
	}
	if tree {
		writeMembers(&b, def)
	}
	b.WriteString("\n## Rejected\n\n")
	rejected := 0
	for _, v := range verdicts {
		if v.OK {
			continue
		}
		rejected++
		fmt.Fprintf(&b, "- %s `%s`: %s\n", v.Stratum, v.Candidate.Row.Package,
			strings.ReplaceAll(strings.TrimPrefix(v.Reason, pin.RejectedPrefix), "|", "\\|"))
	}
	for _, s := range skipped {
		rejected++
		b.WriteString("- " + strings.ReplaceAll(s, "|", "\\|") + "\n")
	}
	if rejected == 0 {
		b.WriteString("None.\n")
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// writeMembers writes the members of every tree taken, each with its own
// estimate.
func writeMembers(b *strings.Builder, def *definition.Definition) {
	b.WriteString("\n## Members\n\nEach tree's packages with their own estimate; the tree's rebuild_tokens is their sum.\n")
	for _, e := range def.Experiments {
		fmt.Fprintf(b, "\n`%s`:\n\n", e.Package)
		for _, m := range e.Members {
			fmt.Fprintf(b, "- `%s` %s, %.1f passes, %d tokens\n", m.Dir, testedWord(m.HasTests), m.AgentPasses, m.RebuildTokens)
		}
	}
}

// testedWord says whether a package has tests.
func testedWord(tested bool) string {
	if tested {
		return "tested"
	}
	return "untested"
}

// testsCell shortens a long oracle test list for the report table.
func testsCell(pats []string) string {
	if len(pats) <= 3 {
		return "`" + strings.Join(pats, " ") + "`"
	}
	return fmt.Sprintf("`%s` and %d more", strings.Join(pats[:3], " "), len(pats)-3)
}
