package load

import (
	"go/ast"
	"go/parser"
	"go/token"
	"maps"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

// TestSourceSyntaxCgo checks that a cgo package is measured from the files
// in GoFiles, not the files cgo generated into the build cache: the trees
// SourceSyntax and AuthoredSyntax return name exactly GoFiles, while the
// type-checked p.Syntax does not. A pure Go package keeps p.Syntax itself.
func TestSourceSyntaxCgo(t *testing.T) {
	if !haveCgo(t) {
		t.Skip("cgo or its C compiler is unavailable")
	}
	m, err := Load(&packages.Config{Dir: cgoRoot(t)}, packages.Load)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	native := m.Pkgs["example.com/cgo/native"]
	if m.syntaxIsSource(native) {
		t.Fatalf("native: p.Syntax is its source files %v; the fixture no longer exercises cgo", native.GoFiles)
	}
	for name, files := range map[string][]*ast.File{
		"SourceSyntax":   m.SourceSyntax(native),
		"AuthoredSyntax": m.AuthoredSyntax(native),
	} {
		names := make([]string, 0, len(files))
		for _, f := range files {
			names = append(names, m.Fset.File(f.FileStart).Name())
		}
		if !slices.Equal(names, native.GoFiles) {
			t.Errorf("native: %s files = %v, want GoFiles %v", name, names, native.GoFiles)
		}
	}

	user := m.Pkgs["example.com/cgo/user"]
	if got := m.SourceSyntax(user); !slices.Equal(got, user.Syntax) {
		t.Errorf("user: SourceSyntax is not p.Syntax for a package without cgo")
	}
}

// TestGeneratedFiles checks that AuthoredSyntax leaves out exactly the files
// GeneratedNames lists, those with a generated-file header, and that a nil
// Module reads p.Syntax in p.Fset.
func TestGeneratedFiles(t *testing.T) {
	fset := token.NewFileSet()
	var files []*ast.File
	for _, src := range []struct{ name, text string }{
		{"hand.go", "package p\n"},
		{"gen.go", "// Code generated by x. DO NOT EDIT.\n\npackage p\n"},
		{"more.go", "package p\n"},
	} {
		f, err := parser.ParseFile(fset, filepath.Join("/m", src.name), src.text, parser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, f)
	}
	p := &packages.Package{PkgPath: "example.com/m/p", Syntax: files, Fset: fset}
	for _, m := range []*Module{nil, {Fset: fset}} {
		if got := m.AuthoredSyntax(p); !slices.Equal(got, []*ast.File{files[0], files[2]}) {
			t.Errorf("AuthoredSyntax = %d files, want hand.go and more.go", len(got))
		}
		if got := slices.Sorted(maps.Keys(m.GeneratedNames(p))); !slices.Equal(got, []string{filepath.Join("/m", "gen.go")}) {
			t.Errorf("GeneratedNames = %v, want gen.go", got)
		}
	}
	plain := &packages.Package{Syntax: []*ast.File{files[0]}, Fset: fset}
	if got := (*Module)(nil).AuthoredSyntax(plain); len(got) != 1 || &got[0] != &plain.Syntax[0] {
		t.Error("AuthoredSyntax copied a package without generated files")
	}
	if got := (*Module)(nil).GeneratedNames(plain); got != nil {
		t.Errorf("GeneratedNames = %v, want nil", got)
	}
}

// TestLoadIndexesTestPackages checks the fixture's test variants: the
// in-package and external test packages are indexed under the package they
// test, never as packages of their own, and TestPackages returns them in
// that order.
func TestLoadIndexesTestPackages(t *testing.T) {
	m := loadFixture(t)
	if m.Path != "example.com/fixture" || m.Fset == nil {
		t.Fatalf("Path = %q, Fset = %v, want example.com/fixture and a file set", m.Path, m.Fset)
	}
	for _, path := range m.Paths {
		if strings.HasSuffix(path, "_test") || strings.HasSuffix(path, ".test") {
			t.Errorf("Paths holds test package %s", path)
		}
	}
	tested := m.Pkgs["example.com/fixture/tested"]
	got := m.TestPackages(tested)
	if len(got) != 2 || got[0] != m.Tests[tested.PkgPath] || got[1] != m.XTests[tested.PkgPath] {
		t.Fatalf("TestPackages(tested) = %d packages, want its test variant and external test package", len(got))
	}
	if got[1].PkgPath != "example.com/fixture/tested_test" {
		t.Errorf("external test PkgPath = %q, want example.com/fixture/tested_test", got[1].PkgPath)
	}
	if got := m.TestPackages(m.Pkgs["example.com/fixture/a"]); len(got) != 0 {
		t.Errorf("TestPackages(a) = %d packages, want none", len(got))
	}
}

// TestLoadEmptyModule checks that a module without packages loads with no
// Paths and no error, so the caller names it.
func TestLoadEmptyModule(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "go.mod"), "module example.com/empty\n\ngo 1.27\n")
	m, err := Load(&packages.Config{Dir: dir}, packages.Load)
	if err != nil || len(m.Paths) != 0 {
		t.Fatalf("Load = %v, %v, want no packages and no error", m, err)
	}
}

// TestStdPackage loads one standard-library package on its own.
func TestStdPackage(t *testing.T) {
	m, err := StdPackage(t.Context(), packages.Load, "unicode/utf8")
	if err != nil {
		t.Skipf("no usable GOROOT sources: %v", err)
	}
	if m.Path != StdModulePath || !slices.Equal(m.Paths, []string{"unicode/utf8"}) {
		t.Errorf("Path = %q, Paths = %v, want %q and [unicode/utf8]", m.Path, m.Paths, StdModulePath)
	}
	if len(m.TestPackages(m.Pkgs["unicode/utf8"])) == 0 {
		t.Error("unicode/utf8 has no test packages")
	}
}

// TestStdlibLeavesOutFailures feeds Stdlib a load of three packages, one
// with an error, and checks that the failing package and its test variant
// are left out and returned as failures, and that test mains are dropped.
func TestStdlibLeavesOutFailures(t *testing.T) {
	pkg := func(id, path string, errs ...packages.Error) *packages.Package {
		return &packages.Package{ID: id, PkgPath: path, Errors: errs}
	}
	roots := []*packages.Package{
		pkg("bytes", "bytes"),
		pkg("bytes [bytes.test]", "bytes"),
		pkg("bytes.test", "bytes.test"),
		pkg("broken", "broken", packages.Error{Msg: "broken.go:1:1: bad"}),
		pkg("broken [broken.test]", "broken"),
		pkg("fmt", "fmt"),
	}
	fake := func(*packages.Config, ...string) ([]*packages.Package, error) { return roots, nil }
	m, failed, err := Stdlib(t.Context(), fake)
	if err != nil {
		t.Fatalf("Stdlib: %v", err)
	}
	if m.Path != StdAllModulePath || !slices.Equal(m.Paths, []string{"bytes", "fmt"}) {
		t.Errorf("Path = %q, Paths = %v, want %q and [bytes fmt]", m.Path, m.Paths, StdAllModulePath)
	}
	if len(m.Tests) != 1 || m.Tests["bytes"] == nil {
		t.Errorf("Tests = %v, want bytes only", m.Tests)
	}
	if err := failed["broken"]; err == nil || !strings.Contains(err.Error(), "loading broken: ") || len(failed) != 1 {
		t.Errorf("failed = %v, want broken alone", failed)
	}

	none := func(*packages.Config, ...string) ([]*packages.Package, error) { return nil, nil }
	if m, _, err := Stdlib(t.Context(), none); err != nil || len(m.Paths) != 0 {
		t.Errorf("Stdlib of an empty load = %v, %v, want no packages and no error", m, err)
	}
}
