// Package report renders the Markdown gate-validation report that
// calibration/validate writes: the gate's recall and false-failure rate on
// labeled commits against the SPEC.md 14 targets, each rule's precision
// and recall per corpus beside a size-only rule, each rule's sweep, a
// recommendation per rule, and the block commits the gate missed.
package report

import (
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/rfizzle/astimate/calibration/replay/labels"
	"github.com/rfizzle/astimate/calibration/validate/internal/corpus"
	"github.com/rfizzle/astimate/calibration/validate/internal/measure"
)

// Targets are the SPEC.md 14 targets: fail at least Recall of block
// commits and at most FalseFailure of allow commits.
type Targets struct {
	Recall, FalseFailure float64
}

// Corpus describes one input corpus.
type Corpus struct {
	// Source names the corpus and its files.
	Source corpus.Source
	// Loaded is the corpus as joined.
	Loaded *corpus.Corpus
	// SetAside is the number of capacity-only block labels.
	SetAside int
	// Checked and Mismatched are measure.Scored.Recheck's counts.
	Checked, Mismatched int
}

// View is one corpus or pool of corpora as scored.
type View struct {
	Name string
	// Gate is the gate as replayed; Advised the gate with every
	// recommendation applied; Size the size-only rule at Input.SizeT.
	Gate, Advised, Size measure.Rates
	// Rules and Judged are each rule's rates and the commits with a row it
	// judges, indexed like Input.Rules.
	Rules  []measure.Rates
	Judged []int
}

// Missed lists one corpus's block commits the gate passed.
type Missed struct {
	Corpus  string
	Commits []*corpus.Commit
}

// Legacy is one capacity rule's firings on Basis and those that were
// growth in a package already over its max.
type Legacy struct {
	// Rule indexes Input.Rules.
	Rule        int
	Fired, Over measure.Rates
}

// Input is what the report describes.
type Input struct {
	// Date is the report's date; Version the configuration's
	// config_version and ConfigSource where it came from.
	Date, Version, ConfigSource string
	// AgentOnly says labels with agent: false were dropped.
	AgentOnly bool
	Targets   Targets
	Corpora   []Corpus
	// Views are the corpora one by one, the set-aside views and the
	// pools; the last is the basis for the size threshold, the sweeps and
	// the advice.
	Views []View
	// Rules are the gated rules.
	Rules []measure.Rule
	// SizeT is the size-only threshold picked on the basis, SizeMet
	// whether it meets the false-failure target, SizeCurve the size-only
	// sweep there.
	SizeT     int
	SizeMet   bool
	SizeCurve []measure.SizePoint
	// Curves, Dropped and Advice are per rule, on the basis: its sweeps,
	// the gate's rates without it, and its recommendation.
	Curves   [][]measure.Curve
	Dropped  []measure.Rates
	Advice   []measure.Advice
	Criteria measure.Criteria
	// Legacy holds measure.Scored.Legacy on the basis for each capacity
	// rule.
	Legacy []Legacy
	Missed []Missed
}

// basis is the view the sweeps and advice use.
func (in *Input) basis() *View { return &in.Views[len(in.Views)-1] }

// Render returns the report as Markdown.
func Render(in *Input) string {
	var b strings.Builder
	sections := []func(*strings.Builder, *Input){header, method, headline, corpora, perRule, size, sweeps, legacy, advice, missed}
	for _, section := range sections {
		section(&b, in)
	}
	return b.String()
}

// header writes the title and the inputs.
func header(b *strings.Builder, in *Input) {
	fmt.Fprintf(b, "# Gate validation %s\n\n- Configuration: `%s` (%s)\n", in.Date, in.Version, in.ConfigSource)
	for _, c := range in.Corpora {
		fmt.Fprintf(b, "- Corpus `%s`: rows `%s`, labels `%s`\n", c.Source.Name, c.Source.Data, c.Source.Labels)
	}
	b.WriteString("- Generated by `go run ./calibration/validate`\n\n")
}

// method writes how the numbers are computed.
func method(b *strings.Builder, in *Input) {
	agent := "every label is scored"
	if in.AgentOnly {
		agent = "a label with `agent: false` (a commit no coding agent took part in) is dropped, so the numbers describe agent-authored changes"
	}
	checked, mismatched := 0, 0
	for _, c := range in.Corpora {
		checked += c.Checked
		mismatched += c.Mismatched
	}
	ruleBlock, reverts := 0, 0
	for _, c := range in.Corpora {
		for i := range c.Loaded.Commits {
			cm := &c.Loaded.Commits[i]
			if !c.Loaded.RuleLabels || !cm.Block() {
				continue
			}
			ruleBlock++
			if slices.ContainsFunc(cm.Label.Fired, func(e labels.Evidence) bool { return e.Part == labels.PartRevert }) {
				reverts++
			}
		}
	}
	fmt.Fprintf(b, methodText, agent, pct(in.Targets.Recall), pct(in.Targets.FalseFailure), mismatched, checked,
		pct(in.Targets.FalseFailure), in.basis().Name, ruleBlock, reverts)
}

// headline writes the gate's recall and false-failure rate per view.
func headline(b *strings.Builder, in *Input) {
	t := in.Targets
	fmt.Fprintf(b, "## Headline\n\nThe size-only rule is `sloc_delta > %d`.\n\n", in.SizeT)
	rows := make([][]string, 0, len(in.Views))
	for _, v := range in.Views {
		row := []string{v.Name, frac(v.Gate.BlockFailed, v.Gate.Block), met(v.Gate.Recall() >= t.Recall),
			frac(v.Gate.AllowFailed, v.Gate.Allow), met(v.Gate.FalseFailure() <= t.FalseFailure)}
		row = append(row, frac(v.Size.BlockFailed, v.Size.Block), frac(v.Size.AllowFailed, v.Size.Allow))
		rows = append(rows, append(row, shares(v.Advised)...))
	}
	table(b, []string{"View", "Gate recall", "≥ " + pct(t.Recall), "Gate false failures", "≤ " + pct(t.FalseFailure),
		"Size-only recall", "Size-only false failures", "Advised recall", "Advised false failures"}, rows)
	b.WriteString("Advised is the gate re-evaluated with every recommendation of this report applied (Recommendations), the other rules as recorded.\n\n")
	v := in.basis()
	fmt.Fprintf(b, "On the %s view the gate fails %s of `block` commits against a target of at least %s (%s) and %s of `allow` commits against a target of at most %s (%s). ",
		v.Name, pct(v.Gate.Recall()), pct(t.Recall), met(v.Gate.Recall() >= t.Recall),
		pct(v.Gate.FalseFailure()), pct(t.FalseFailure), met(v.Gate.FalseFailure() <= t.FalseFailure))
	fmt.Fprintf(b, "The size-only rule at %d SLOC fails %s and %s. With every recommendation below applied, the gate would fail %s and %s.\n\n",
		in.SizeT, pct(v.Size.Recall()), pct(v.Size.FalseFailure()), pct(v.Advised.Recall()), pct(v.Advised.FalseFailure()))
	top := in.SizeCurve[0]
	for _, p := range in.SizeCurve {
		if p.Rates.J() > top.Rates.J() {
			top = p
		}
	}
	fmt.Fprintf(b, "What the metrics add over the size of the change: the gate's J (recall minus false-failure rate) is %s; the size-only rule's best J is %s, at `sloc_delta > %d` (%s).\n\n",
		pts(v.Gate.J()), pts(top.Rates.J()), top.T, strings.Join(shares(top.Rates), " and "))
	var ruled []string
	for _, c := range in.Corpora {
		if c.Loaded.RuleLabels {
			ruled = append(ruled, code(c.Source.Name))
		}
		if c.SetAside > 0 {
			block, _ := c.Loaded.Counts()
			fmt.Fprintf(b, "`%s` has %d capacity-only `block` labels. Its honest numbers are the view with them set aside, since the gate reads the same sizes those labels were drawn from; %d `block` labels remain there, so one commit moves its recall by %s points.\n\n",
				c.Source.Name, c.SetAside, block-c.SetAside, strconv.FormatFloat(100*share(1, block-c.SetAside), 'f', 1, 64))
		}
	}
	if len(ruled) > 0 {
		fmt.Fprintf(b, "The `block` labels of %s are fix-ups (Method): their recall is the share of changes a later fix touched that the gate failed, and their `allow` labels include every bad change nobody fixed within 20 commits, which inflates the false-failure rate by an unknown amount.\n\n", strings.Join(ruled, ", "))
	}
}

// corpora writes the per-corpus counts.
func corpora(b *strings.Builder, in *Input) {
	b.WriteString("## Corpora\n\n")
	rows := make([][]string, 0, len(in.Corpora))
	for _, c := range in.Corpora {
		kind := "hand"
		if c.Loaded.RuleLabels {
			kind = "rule (fix-up or revert)"
		}
		block, allow := c.Loaded.Counts()
		rows = append(rows, append([]string{c.Source.Name, kind}, ints(c.Loaded.Labeled, c.Loaded.NotLoaded, c.Loaded.NotAgent, block, allow, c.SetAside)...))
	}
	table(b, []string{"Corpus", "Labels", "Labeled", "Not loaded", "Dropped, not agent", "`block` scored", "`allow` scored", "Capacity-only `block`"}, rows)
}

// perRule writes one table per view with every rule and the size-only
// rule.
func perRule(b *strings.Builder, in *Input) {
	fmt.Fprintf(b, "## Per rule\n\nOne table for each of the %d views. Fired counts commits, not rows. A rule that judged no row of a view shows no rates.\n\n", len(in.Views))
	for _, v := range in.Views {
		fmt.Fprintf(b, "### %s\n\n", v.Name)
		rows := make([][]string, 0, len(in.Rules)+2)
		for i, r := range in.Rules {
			if v.Judged[i] == 0 {
				rows = append(rows, []string{code(r.Name()), "no rows", "", "", "", ""})
				continue
			}
			rows = append(rows, rateRow(code(r.Name()), v.Rules[i]))
		}
		rows = append(rows, rateRow("gate (any rule)", v.Gate), rateRow("size-only, "+code("sloc_delta > "+strconv.Itoa(in.SizeT)), v.Size))
		table(b, []string{"Rule", "Fired on `block`", "Fired on `allow`", "Precision", "Recall", "False-failure share"}, rows)
	}
}

// rateRow is one row of a per-rule table.
func rateRow(name string, r measure.Rates) []string {
	prec := "none fired"
	if p, ok := r.Precision(); ok {
		prec = pct(p)
	}
	return append([]string{name, strconv.Itoa(r.BlockFailed), strconv.Itoa(r.AllowFailed), prec}, shares(r)...)
}

// size writes the size-only sweep.
func size(b *strings.Builder, in *Input) {
	fmt.Fprintf(b, "## Size-only baseline\n\nOne rule on the change's size, swept on the %s view: fail a commit when a package's `sloc_delta` exceeds t.\n\n", in.basis().Name)
	rows := make([][]string, 0, len(in.SizeCurve))
	for _, p := range in.SizeCurve {
		rows = append(rows, append([]string{strconv.Itoa(p.T)}, append(shares(p.Rates), pts(p.Rates.J()))...))
	}
	table(b, []string{"t", "Recall", "False failures", "J"}, rows)
	if in.SizeMet {
		fmt.Fprintf(b, "Best t: %d, the highest recall with false failures at most %s.\n\n", in.SizeT, pct(in.Targets.FalseFailure))
		return
	}
	fmt.Fprintf(b, "No t keeps false failures at or under %s; t %d has the highest J.\n\n", pct(in.Targets.FalseFailure), in.SizeT)
}

// sweeps writes each rule's tradeoff tables.
func sweeps(b *strings.Builder, in *Input) {
	fmt.Fprintf(b, "## Sweeps\n\nOn the %s view. Recall and false-failure contribution are the rule's own; the gate columns hold every other rule as shipped. The shipped setting is marked with *.\n\n", in.basis().Name)
	for i, r := range in.Rules {
		fmt.Fprintf(b, "### %s\n\n", code(r.Name()))
		if len(in.Curves[i]) == 0 || in.basis().Judged[i] == 0 {
			b.WriteString("Nothing to sweep: no limit, or no row it judges.\n\n")
			continue
		}
		var rows [][]string
		for _, c := range in.Curves[i] {
			for _, p := range c.Points {
				name := p.Setting.String()
				if p.Shipped {
					name += " *"
				}
				rows = append(rows, append(append([]string{name}, shares(p.Rule)...), append([]string{pts(p.Rule.J())}, shares(p.Gate)...)...))
			}
		}
		rows = append(rows, append([]string{"rule dropped", "", "", ""}, shares(in.Dropped[i])...))
		table(b, []string{"Setting", "Recall contribution", "False-failure contribution", "J", "Gate recall", "Gate false failures"}, rows)
	}
}

// legacy writes how many capacity firings were growth in a package already
// over the ceiling.
func legacy(b *strings.Builder, in *Input) {
	if len(in.Legacy) == 0 {
		return
	}
	fmt.Fprintf(b, "## Capacity rules on packages already over the ceiling\n\n"+legacyText, in.basis().Name)
	rows := make([][]string, 0, len(in.Legacy))
	for _, l := range in.Legacy {
		counts := ints(l.Fired.Block, l.Fired.Allow, l.Over.Block, l.Over.Allow)
		rows = append(rows, append(append([]string{code(in.Rules[l.Rule].Name())}, counts...), frac(l.Over.Failed(), l.Fired.Failed())))
	}
	table(b, []string{"Rule", "Fired on `block`", "Fired on `allow`", "Already over, `block`", "Already over, `allow`", "Already over, share"}, rows)
}

// advice writes the recommendation per rule.
func advice(b *strings.Builder, in *Input) {
	fmt.Fprintf(b, "## Recommendations\n\n"+adviceText, in.basis().Name, in.Criteria.MinFired, pct(in.Criteria.Budget), pts(in.Criteria.MinJ))
	rows := make([][]string, 0, len(in.Rules))
	for i, r := range in.Rules {
		a := in.Advice[i]
		to, why := "", a.Why
		if a.Action == measure.Retune {
			to = a.To.String()
		}
		for _, l := range in.Legacy {
			if l.Rule == i && a.Action != measure.Keep {
				why += "; " + pct(share(l.Over.Failed(), l.Fired.Failed())) + " of the commits it fired on only grew a package already over its max, which no retuned max prevents"
			}
		}
		rows = append(rows, []string{code(r.Name()), string(a.Action), to, why})
	}
	table(b, []string{"Rule", "Action", "To", "Why"}, rows)
}

// missed writes the block commits the gate passed, per corpus.
func missed(b *strings.Builder, in *Input) {
	b.WriteString("## Missed `block` commits\n\nThe `block` commits each corpus's gate passed, with the label's reason.\n\n")
	for _, m := range in.Missed {
		rows := make([][]string, len(m.Commits))
		for i, c := range m.Commits {
			rows[i] = []string{code(c.Hash[:min(12, len(c.Hash))]), c.Subject, c.Label.Reason}
		}
		b.WriteString("### " + m.Corpus + "\n\n")
		if len(rows) > 0 {
			table(b, []string{"Commit", "Subject", "Label reason"}, rows)
		} else {
			b.WriteString("None.\n\n")
		}
	}
}
