package inspect

import (
	"go/ast"
	"go/parser"
	"go/token"
	"strconv"
	"testing"

	"github.com/rfizzle/astimate/internal/lang/golang/internal/load"
	"golang.org/x/tools/go/packages"
)

// opacityOf parses srcs as the non-test files of one package and returns
// its opacity flags.
func opacityOf(t *testing.T, srcs ...string) OpacityFlags {
	t.Helper()
	fset := token.NewFileSet()
	files := make([]*ast.File, 0, len(srcs))
	for i, src := range srcs {
		f, err := parser.ParseFile(fset, "f"+strconv.Itoa(i)+".go", src, parser.ParseComments)
		if err != nil {
			t.Fatalf("parsing: %v", err)
		}
		files = append(files, f)
	}
	return Opacity(&load.Module{Fset: fset}, &packages.Package{PkgPath: "example.com/m/p", Syntax: files})
}

// TestGeneratedHeader pins the header rule behind generated_files: a line
// matching ^// Code generated .* DO NOT EDIT\.$ before the package clause,
// which ast.IsGenerated implements.
func TestGeneratedHeader(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want int
	}{
		{"canonical", "// Code generated by stringer; DO NOT EDIT.\n\npackage p\n", 1},
		{"fixture header", "// Code generated by hand for the fixture. DO NOT EDIT.\n\npackage p\n", 1},
		{"after a doc comment", "// Copyright 2026.\n\n// Code generated by x. DO NOT EDIT.\n\npackage p\n", 1},
		{"block comment", "/*\n// Code generated by x. DO NOT EDIT.\n*/\npackage p\n", 1},
		{"no period", "// Code generated by x. DO NOT EDIT\n\npackage p\n", 0},
		{"lower case", "// code generated by x. DO NOT EDIT.\n\npackage p\n", 0},
		{"trailing text", "// Code generated by x. DO NOT EDIT. Really.\n\npackage p\n", 0},
		{"nothing between", "// Code generated DO NOT EDIT.\n\npackage p\n", 0},
		{"after the package clause", "package p\n\n// Code generated by x. DO NOT EDIT.\n", 0},
		{"hand written", "// Package p is written by hand.\npackage p\n", 0},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := opacityOf(t, tc.src).Generated; got != tc.want {
				t.Errorf("generated_files = %d, want %d", got, tc.want)
			}
		})
	}
	if got := opacityOf(t, cases[0].src, cases[1].src, cases[len(cases)-1].src).Generated; got != 2 {
		t.Errorf("generated_files over three files = %d, want 2", got)
	}
}

func TestOpacityImports(t *testing.T) {
	cases := []struct {
		name         string
		src          string
		cgo, reflect bool
	}{
		{"none", "package p\n\nimport \"strings\"\n", false, false},
		{"cgo", "package p\n\n// #include <stdio.h>\nimport \"C\"\n", true, false},
		{"reflect", "package p\n\nimport \"reflect\"\n", false, true},
		{"unsafe", "package p\n\nimport \"unsafe\"\n", false, true},
		{"blank unsafe", "package p\n\nimport _ \"unsafe\"\n", false, true},
		{"renamed reflect", "package p\n\nimport r \"reflect\"\n", false, true},
		{"raw string path", "package p\n\nimport `unsafe`\n", false, true},
		{"cgo and unsafe", "package p\n\nimport (\n\t\"C\"\n\t\"unsafe\"\n)\n", true, true},
		{"reflect lookalike", "package p\n\nimport \"example.com/reflect\"\n", false, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := opacityOf(t, tc.src)
			if got.Cgo != tc.cgo || got.Reflect != tc.reflect {
				t.Errorf("uses_cgo, uses_reflect = %v, %v, want %v, %v", got.Cgo, got.Reflect, tc.cgo, tc.reflect)
			}
		})
	}
}
