package golang

import (
	"go/ast"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/rfizzle/astimate/internal/metrics"
)

// Sources of the generated-file module: gen.go declares everything the
// size and structure metrics count, behind a generated-file header, and is
// the only file importing strconv and the module's other package.
const (
	genHand = `package p

// Exported is written by hand.
func Exported(n int) int {
	if n > 0 {
		return n
	}
	return -n
}

var state int
`
	genGenerated = `// Code generated by a test. DO NOT EDIT.

package p

import (
	"strconv"

	"example.com/gen/q"
)

// Table is generated.
var Table = map[string]int{"a": 1, "b": 2}

// Generated is generated.
type Generated struct{}

// Lookup is generated.
func (Generated) Lookup(s string) int {
	for k, v := range Table {
		if k == s {
			if v > 1 {
				return v
			}
		}
	}
	return 0
}

// Format is generated.
func Format(n int) string { return strconv.Itoa(n) + q.Suffix }

func init() { Table["c"] = 3 }
`
	genTest = `package p

import "testing"

func TestNothing(t *testing.T) {}
`
	genQ = `package q

// Suffix is imported only by a generated file.
const Suffix = "!"
`
)

// TestGeneratedFileExcluded checks SPEC.md 6.5: a generated non-test file
// counts in files, generated_files, tokens_est_generated and the import
// metrics, and in no size or structure metric, the function list and the
// untested names included.
func TestGeneratedFileExcluded(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "go.mod"), "module example.com/gen\n\ngo 1.27\n")
	for _, sub := range []string{"p", "q"} {
		if err := os.Mkdir(filepath.Join(dir, sub), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, filepath.Join(dir, "p", "hand.go"), genHand)
	writeFile(t, filepath.Join(dir, "p", "zz_gen.go"), genGenerated)
	writeFile(t, filepath.Join(dir, "p", "p_test.go"), genTest)
	writeFile(t, filepath.Join(dir, "q", "q.go"), genQ)

	e := New(WithCharsPerToken(1))
	mod := &metrics.ModuleContext{Root: dir}
	m, err := e.Extract(t.Context(), mod, "example.com/gen/p")
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	ints := []struct {
		name      string
		got, want int
	}{
		{"files", m.Files, 2},
		{"sloc", m.SLOC, 8},
		{"largest_file_sloc", m.LargestFileSLOC, 8},
		{"tokens_est", m.TokensEst, len(genHand)},
		{"tokens_est_with_tests", m.TokensEstWithTests, len(genHand) + len(genTest)},
		{"exported_symbols", m.ExportedSymbols, 1},
		{"globals", m.Globals, 1},
		{"init_funcs", m.InitFuncs, 0},
		{"func_count", m.FuncCount, 1},
		{"cognitive_total", m.CognitiveTotal, 1},
		{"cognitive_p90", m.CognitiveP90, 1},
		{"max_nesting", m.MaxNesting, 1},
		{"untested_exports", m.UntestedExports, 1},
		{"dup_blocks", m.DupBlocks, 0},
		// Imports are read from every file: strconv and q come from the
		// generated file only.
		{"stdlib_imports", m.StdlibImports, 1},
		{"internal_imports", m.InternalImports, 1},
	}
	for _, c := range ints {
		if c.got != c.want {
			t.Errorf("%s = %d, want %d", c.name, c.got, c.want)
		}
	}
	if m.GeneratedFiles == nil || *m.GeneratedFiles != 1 {
		t.Errorf("generated_files = %v, want 1", m.GeneratedFiles)
	}
	if m.TokensEstGenerated == nil || *m.TokensEstGenerated != len(genGenerated) {
		t.Errorf("tokens_est_generated = %v, want %d", m.TokensEstGenerated, len(genGenerated))
	}
	if m.Abstractness != nil {
		t.Errorf("abstractness = %v, want null: the only exported type is generated", *m.Abstractness)
	}

	q, err := e.Extract(t.Context(), mod, "example.com/gen/q")
	if err != nil {
		t.Fatalf("Extract(q): %v", err)
	}
	if q.FanIn != 1 {
		t.Errorf("q fan_in = %d, want 1: the generated file's import is an edge", q.FanIn)
	}
	if q.TokensEstGenerated == nil || *q.TokensEstGenerated != 0 {
		t.Errorf("q tokens_est_generated = %v, want 0", q.TokensEstGenerated)
	}

	det, err := e.Details(t.Context(), mod, "example.com/gen/p")
	if err != nil {
		t.Fatalf("Details: %v", err)
	}
	if !slices.Equal(det.UntestedExports, []string{"Exported"}) {
		t.Errorf("untested names = %q, want [Exported]", det.UntestedExports)
	}
	if !slices.Equal(det.GlobalNames, []string{"state"}) {
		t.Errorf("global names = %q, want [state]", det.GlobalNames)
	}
	if det.LargestFile != "hand.go" {
		t.Errorf("largest file = %q, want hand.go", det.LargestFile)
	}
	if !slices.Equal(det.SourceFiles, []string{"hand.go", "zz_gen.go"}) {
		t.Errorf("source files = %q, want both files", det.SourceFiles)
	}
	fns, err := e.Functions(t.Context(), mod, "example.com/gen/p")
	if err != nil {
		t.Fatalf("Functions: %v", err)
	}
	if len(fns) != 1 || fns[0].Name != "Exported" {
		t.Errorf("functions = %+v, want Exported only", fns)
	}
}

// TestHubMatchesHandWrittenFiles checks the fixture's hub against its
// hand-written file alone: sloc and exported_symbols are those of hub.go,
// as if zz_generated.go were absent.
func TestHubMatchesHandWrittenFiles(t *testing.T) {
	root := fixtureRoot(t)
	l := loadFixture(t)
	p := l.pkgs["example.com/fixture/hub"]
	var hand *ast.File
	for _, f := range sourceSyntax(l, p) {
		if filepath.Base(l.fset.File(f.FileStart).Name()) == "hub.go" {
			hand = f
		}
	}
	if hand == nil {
		t.Fatal("hub.go not in the fixture load")
	}
	name := filepath.Join(root, "hub", "hub.go")
	data, err := os.ReadFile(name)
	if err != nil {
		t.Fatal(err)
	}
	m, err := New().Extract(t.Context(), &metrics.ModuleContext{Root: root}, "example.com/fixture/hub")
	if err != nil {
		t.Fatalf("Extract: %v", err)
	}
	if want := fileSLOC(l.fset.File(hand.FileStart), hand, data); m.SLOC != want {
		t.Errorf("hub sloc = %d, want hub.go's %d", m.SLOC, want)
	}
	if want := exportedSymbols(hand, p.Types.Scope()).symbols; m.ExportedSymbols != want {
		t.Errorf("hub exported_symbols = %d, want hub.go's %d", m.ExportedSymbols, want)
	}
}
