package main

import (
	"cmp"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/rfizzle/astimate/internal/gate"
	"github.com/rfizzle/astimate/internal/metrics"
)

// reportInput is what the Markdown report describes.
type reportInput struct {
	// Version is the candidate's config_version.
	Version string
	// BaseVersion is the base configuration's config_version.
	BaseVersion string
	// Data and Candidate are the input rows and output config paths.
	Data, Candidate string
	// Rows is the number of pooled rows; Modules the distinct modules.
	Rows    int
	Modules []string
	// Provisional says the data holds only the standard library.
	Provisional bool
	// Choices are the fitted rules in config order.
	Choices []Choice
	// CrossPkg is the distribution of dup_blocks_cross_pkg over the
	// data's module rows; its N is 0 when the data has none.
	CrossPkg Stats
}

// methodText states the fitting rules; the report header and the
// candidate's leading comment both carry it.
func methodText() []string {
	return []string{
		"Percentiles are nearest-rank: the p-th percentile of n values is the value at rank ceil(p/100 * n), so it is always an observed value. IQR is p75 minus p25.",
		"A capacity rule's max, and a density rule's max where the base rule has one, is the 90th percentile rounded to two significant figures and then to the nearest readable step: 500 above 1000, 50 above 100, 5 above 10, otherwise 1 (0.5 for a percentage). A capacity max is at least one step.",
		"A density rule's max_delta is a quarter of the IQR rounded up to a whole step, at least 1 for a count and 0.5 for a percentage, except that a rule whose base max_delta is 0 keeps it: zero tolerance on new duplicate blocks, untested exports, globals, init functions and nesting is a policy, not a statistic.",
		"internal_imports is pooled from cloned-module rows only, since the standard library is loaded as one module and counts every standard-library import as internal; every other metric is pooled from all rows.",
		"Kinds, warn_at, ratchet_from_zero, when guards, requirement rules, the rebuild parameters and every other key are copied from the base unchanged; a density rule with no max in the base gets none.",
	}
}

// renderReport writes the Markdown report.
func renderReport(in *reportInput) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Threshold candidate %s\n\n", in.Version)
	if in.Provisional {
		w("**Provisional.** Every pooled row is from the Go standard library; no external module has been collected yet. ")
		w("This candidate is not the shipped default and must not replace it; refit once the corpus in `calibration/corpus.yaml` is collected.\n\n")
	}
	w("- Data: `%s`, %d packages from %d module(s): %s\n", in.Data, in.Rows, len(in.Modules), strings.Join(quoted(in.Modules), ", "))
	w("- Base configuration: `%s`\n", in.BaseVersion)
	w("- Candidate: `%s`\n", in.Candidate)
	w("- Generated by `go run ./calibration/fit`\n\n")

	w("## Method\n\n")
	for _, line := range methodText() {
		w("- %s\n", line)
	}
	w("\n\"Fail as new\" counts pooled packages that would violate the rule as a package new at head, with no baseline: ")
	w("above max, above max_delta from zero where ratchet_from_zero is set, or not meeting a requirement whose guard holds.\n\n")

	w("## Summary\n\n")
	w("Base is `%s`, candidate `%s`. Rows counts the rows the metric was measured on and names which rows fed it.\n\n",
		in.BaseVersion, in.Version)
	w("| Metric | Kind | Rows | p90 | IQR | Base max | Candidate max | Base max_delta | Candidate max_delta | Fail as new, base | Fail as new, candidate |\n")
	w("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n")
	for i := range in.Choices {
		c := &in.Choices[i]
		p90, iqr := "none", "none"
		if c.Stats.N > 0 {
			p90, iqr = num(c.Stats.P90), num(c.Stats.IQR)
		}
		w("| `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", c.Rule.Metric, c.Rule.Kind, rowsUsed(c),
			p90, iqr, opt(c.Rule.Max), opt(c.Max), opt(c.Rule.MaxDelta), opt(c.MaxDelta),
			share(c.OverBase, c.Stats.N), share(c.OverCandidate, c.Stats.N))
	}
	w("\n")

	w("## What changed most\n\n")
	writeChanges(&b, in)

	w("## Not fitted\n\n")
	writeUnfitted(&b, in)

	w("## Per metric\n\n")
	for i := range in.Choices {
		writeMetric(&b, &in.Choices[i])
	}
	return b.String()
}

// writeChanges writes the moves of the fitted limits, largest first, and
// what the data behind them implies.
func writeChanges(b *strings.Builder, in *reportInput) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format, args...) }
	moved := make([]*Choice, 0, len(in.Choices))
	for i := range in.Choices {
		c := &in.Choices[i]
		if c.Max != nil && c.Rule.Max != nil && *c.Max != *c.Rule.Max {
			moved = append(moved, c)
		}
	}
	slices.SortStableFunc(moved, func(x, y *Choice) int {
		return cmp.Compare(logRatio(*y.Max, *y.Rule.Max), logRatio(*x.Max, *x.Rule.Max))
	})
	for _, c := range moved {
		dir := "loosens"
		if *c.Max < *c.Rule.Max {
			dir = "tightens"
		}
		w("- `%s` max %s: %s to %s. The pooled median is %s and p90 is %s; as new packages, %s of the pool failed the base max and %s fail the candidate.\n",
			c.Rule.Metric, dir, num(*c.Rule.Max), num(*c.Max), num(c.Stats.P50), num(c.Stats.P90),
			share(c.OverBase, c.Stats.N), share(c.OverCandidate, c.Stats.N))
	}
	var moves, pinned []string
	for i := range in.Choices {
		c := &in.Choices[i]
		switch {
		case c.DeltaPinned:
			pinned = append(pinned, "`"+c.Rule.Metric+"`")
		case c.MaxDelta != nil && c.Rule.MaxDelta != nil && *c.MaxDelta != *c.Rule.MaxDelta:
			moves = append(moves, fmt.Sprintf("`%s` %s to %s", c.Rule.Metric, num(*c.Rule.MaxDelta), num(*c.MaxDelta)))
		}
	}
	if len(moves) > 0 {
		w("- max_delta moves on %s: a quarter of each IQR.\n", strings.Join(moves, ", "))
	}
	if len(pinned) > 0 {
		w("- max_delta stays 0 on %s whatever the IQR: zero tolerance on these is a policy, not a statistic (SPEC.md 11.1).\n",
			strings.Join(pinned, ", "))
	}
	w("\n")
	if in.Provisional {
		w("The standard library is the reference for idiomatic Go but not a typical module: it is low level, ")
		w("carries platform variants and literal data tables, and, measured as one module, counts every standard-library import as `internal_imports` (see `calibration/corpus.md`). ")
		w("Limits fitted from it alone describe the standard library, not the ecosystem. ")
		w("The data has no external modules yet; treat every number here as provisional until the corpus run.\n\n")
	}
}

// writeUnfitted names the gated metrics no row measures, which keep their
// base values, and describes the module-wide dup_blocks_cross_pkg, which
// no base rule gates, from the data's module rows or their absence.
func writeUnfitted(b *strings.Builder, in *reportInput) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format, args...) }
	for i := range in.Choices {
		c := &in.Choices[i]
		if c.Stats.N == 0 {
			w("- `%s`: no row measures it, so the base values are kept (max %s, max_delta %s). ",
				c.Rule.Metric, opt(c.Max), opt(c.MaxDelta))
			w("A metric that is itself a diff against a baseline needs baseline and head pairs, which the corpus does not have.\n")
		}
	}
	if s := &in.CrossPkg; s.N == 0 {
		w("- `dup_blocks_cross_pkg`: the data has no `%s` rows, so the module-wide metric has no distribution here and no default rule gates it.\n",
			metrics.ModuleRowID)
	} else {
		w("- `dup_blocks_cross_pkg`, over %d `%s` rows (no default rule gates it): p25 %s, p50 %s, p75 %s, p90 %s, max %s.\n",
			s.N, metrics.ModuleRowID, num(s.P25), num(s.P50), num(s.P75), num(s.P90), num(s.Max))
	}
	w("\n")
}

// rowsUsed describes the rows a metric was measured on: the count and the
// pool.
func rowsUsed(c *Choice) string {
	return strconv.Itoa(c.Stats.N) + ", " + c.Pool
}

// writeMetric writes one metric's section: the rows it was measured on,
// its percentiles, histogram and limits.
func writeMetric(b *strings.Builder, c *Choice) {
	w := func(format string, args ...any) { fmt.Fprintf(b, format, args...) }
	s := &c.Stats
	w("### `%s` (%s)\n\n", c.Rule.Metric, c.Rule.Kind)
	w("Rows: %s.\n\n", rowsUsed(c))
	w("| n | min | p25 | p50 | p75 | p90 | p95 | max | IQR |\n")
	w("| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n")
	w("| %d | %s | %s | %s | %s | %s | %s | %s | %s |\n\n", s.N, num(s.Min), num(s.P25), num(s.P50), num(s.P75),
		num(s.P90), num(s.P95), num(s.Max), num(s.IQR))
	if len(s.Hist) > 0 {
		w("| Range | Packages | Share |\n")
		w("| --- | ---: | ---: |\n")
		closed := len(s.Hist) - 1
		for i, bin := range s.Hist {
			var rng string
			switch {
			case bin.Open:
				rng = "> " + edge(bin.Lo) + " (to " + edge(bin.Hi) + ")"
			case i == closed-1:
				rng = "[" + edge(bin.Lo) + ", " + edge(bin.Hi) + "]"
			default:
				rng = "[" + edge(bin.Lo) + ", " + edge(bin.Hi) + ")"
			}
			w("| %s | %d | %s |\n", rng, bin.Count, pct(bin.Count, s.N))
		}
		w("\n")
	}
	switch c.Rule.Kind {
	case gate.Requirement:
		guard := ""
		if c.Rule.When != nil {
			guard = " when " + c.Rule.When.Metric + " > " + num(c.Rule.When.Value)
		}
		w("Requirement kept: require %t%s. Fail as new: %s.\n\n", c.Rule.Require != nil && *c.Rule.Require, guard,
			share(c.OverCandidate, s.N))
	default:
		w("| | max | max_delta | Fail as new |\n")
		w("| --- | ---: | ---: | ---: |\n")
		w("| Base | %s | %s | %s |\n", opt(c.Rule.Max), opt(c.Rule.MaxDelta), share(c.OverBase, s.N))
		w("| Candidate | %s | %s | %s |\n\n", opt(c.Max), opt(c.MaxDelta), share(c.OverCandidate, s.N))
	}
}

// logRatio is the size of the move from base to v on a log scale, so a
// halving and a doubling rank alike; a zero on either side ranks first.
func logRatio(v, base float64) float64 {
	if v <= 0 || base <= 0 {
		return math.Inf(1)
	}
	return math.Abs(math.Log(v / base))
}

// num formats v with the shortest exact representation.
func num(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}

// edge formats a histogram edge to at most two decimals.
func edge(v float64) string {
	return num(math.Round(v*100) / 100)
}

// opt formats an optional limit, "none" when absent.
func opt(v *float64) string {
	if v == nil {
		return "none"
	}
	return num(*v)
}

// pct formats k of n as a percentage with one decimal.
func pct(k, n int) string {
	if n == 0 {
		return "0%"
	}
	return strconv.FormatFloat(100*float64(k)/float64(n), 'f', 1, 64) + "%"
}

// share formats k of n as "k (p%)".
func share(k, n int) string {
	return strconv.Itoa(k) + " (" + pct(k, n) + ")"
}

// quoted wraps each string in backticks.
func quoted(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	return out
}
